#!/usr/bin/env python

import sys
import os
from subprocess import call

from api import Api

version_string = '0.0.1'
app_name = 'hasit'

api = Api()

def version(args):
    print app_name + ' version ' + version_string + ' Developed by Ashley Coleman'

def help(args):
    print 'hasit {sub} -> get status of sub'
    print 'hasit {sub} [yes/no] -> update {sub} to [yes/no]'
    print 'hasit {sub}[yes/no] {password} -> update {sub} to [yes/no] using {password}'
    print 'hasit create {sub} -> Create sub named {sub}'

def sub(args):
    if len(args) == 2:
        printStatus(args[1])
        return
    if len(args) == 3:
        update(args[1], args[2])
        return
    update(args[1], args[2], args[3])

def printStatus(sub):
    print 'hasit ' + sub + ' today?'
    print api.getStatus(sub)

def update(sub, status, password=None):
    if status != 'yes' and status != 'no':
        print 'I can only update ' + sub + ' to yes or no'
        return

    print 'Updating ' + sub + ' to ' + status
    if password is not None:
        print 'with password ' + password

    api.update(sub, status)

def create(args):
    sub = args[2]
    if sub == '':
        print 'Sub name cannot be empty'
        return
    print api.create(args[2])

commandMap = {
    'version': version,
    'help': help,
    'create' : create
}

try:
    if len(sys.argv) == 1:
        commandMap['help'](sys.argv)
        sys.exit() # Exit script

    commandMap[sys.argv[1]](sys.argv)
except: # Process {sub} command
    sub(sys.argv)

## hasit {sub} -> get status of sub
## hasit {sub} yes -> update {sub} to yes
## hasit {sub} no -> update {sub} to no
## hasit {sub}[yes/no] {password} -> update {sub} to [yes/no] with {password} if required
