#!/usr/bin/env python

import sys
import os
from subprocess import call

version_string = '0.0.1'
app_name = 'hasit'

def version(args):
    print app_name + ' version ' + version_string + ' Developed by Ashley Coleman'

def help(args):
    print app_name + ' - help is wip'

commandMap = {
    'version': version,
    'help': help,

}

try:
    if len(sys.argv) == 1:
        commandMap['help'](sys.argv)
        sys.exit() # Exit script

    commandMap[sys.argv[1]](sys.argv)
except: # Command not supported
    print 'Command not recognized'

## hasit {sub}
